class12/ben/movietrailer/movietrailer_app/config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'
  resources :movies do
    resources :trailers
  end

  get 'trailers' => 'trailers#index'
  get 'about' => 'movies#about'

end

class12/ben/movietrailer/movietrailer_app/app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :trailers, dependent: :destroy

	validates :title, presence: true, length: {minimum: 2}
	validates :year, :presence => true, numericality: {only_integer: true}
	validates :poster_url, :presence => true, length: {minimum: 5}

	# When you're doing an action on the instance that's calling the method, you use self
	# http://stackoverflow.com/questions/10805136/when-to-use-self-in-model
	def self.search(search)
		if search
			where("title LIKE ?", "%#{search}%")
		else
			all
		end
	end

end

class12/ben/movietrailer/movietrailer_app/app/models/trailer.rb
class Trailer < ActiveRecord::Base
	belongs_to :movie

	validates :title, presence: true, length: {minimum: 2}
	validates :embed_url, :presence => true, length: {minimum: 5}
end

class12/ben/movietrailer/movietrailer_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		# get array of years, use search function defined in movie model
		@years = Movie.search(params[:search]).map do |m|
			m.year
		end.uniq.sort.reverse

		@movies = Movie.search(params[:search]).order(:title)
		# binding.pry
	end

	def show
		load_movie
		@trailers = @movie.trailers
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			flash[:notice] = "You have successfully added movie: " + @movie.title
			redirect_to movies_path
		else
			flash.now[:alert] = "Movie not saved"
			render :new
		end
	end

	def edit
		load_movie
	end

	def update
		load_movie
		if @movie.update(movie_params)
			flash[:notice] = "You have successfully updated movie: " + @movie.title
			redirect_to movie_path(@movie)
		else
			flash.now[:alert] = @movie.title + " not updated"
			render :edit
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		flash[:alert] = @movie.title + " was deleted"
		redirect_to movies_path
	end


	private

	def load_movie
		@movie = Movie.find(params[:id])
	end

	def movie_params
		params.require(:movie).permit(:title, :year, :poster_url)
	end

end

class12/ben/movietrailer/movietrailer_app/app/controllers/trailers_controller.rb
class TrailersController < ApplicationController

	before_action :load_movie, except: [:index]
	before_action :load_trailer, except:  [:index, :new, :create]

	def index
		@trailers = Trailer.all
	end

	def show
	end

	def new
		@trailer = Trailer.new
	end

	def create
		@trailer = Trailer.new(trailer_params)
		@trailer.movie = @movie
		if @trailer.save
			flash[:notice] = "You have successfully added trailer: " + @trailer.title
			redirect_to movie_trailer_path(@movie, @trailer)
		else
			flash.now[:alert] = "Trailer not saved"
			render :new
		end
	end

	def edit
	end

	def update
		if @trailer.update(trailer_params)
			flash[:notice] = "You have successfully updated " + @trailer.title
			redirect_to movie_trailer_path(@movie, @trailer)
		else
			flash.now[:alert] = @trailer.title + " not updated"
			render :edit
		end
	end

	def destroy
		@trailer.destroy
		flash[:alert] = @trailer.title + " was deleted"
		redirect_to movie_path(@movie)
	end


	private

	def load_trailer
		@trailer = Trailer.find(params[:id])
	end

	def load_movie
		@movie = Movie.find(params[:movie_id])
	end

	def trailer_params
		# Code to try and parse the youtube URL to grab the embed code. It works, but don't know how to integrate with strong params
		# @embed = params[:trailer][:embed_url].split("=").count > 1 ? params[:trailer][:embed_url].split("=").last : params[:trailer][:embed_url]
		# binding.pry
		params.require(:trailer).permit(:title, :embed_url)
	end

end

class12/ben/movietrailer/movietrailer_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovietrailerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato:100,300,400" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<!-- header -->
<header class="group container">
	
	<h1>
		<%= link_to "movietrail.er", movies_path, :class => "logo" %>
	</h1>

	<nav class="nav">
		<ul>
			<li><%= link_to "Add Movie", new_movie_path %></li>
			<li><%= link_to "View Trailers", trailers_path %></li>
			<li><a href="/about">About</a></li>
		</ul>
	</nav>

	<div class="search"><%= render "movies/search" %></div>

</header>


<!-- display page information -->
<section class="row">
	<div class="group">
		<section class="container">

			<!-- display flash notices if there are any -->
			<% if flash[:notice] %>
				<div class="flash_notice"><%= flash[:notice] %></div>
			<% elsif flash[:alert] %>
				<div class="flash_alert"><%= flash[:alert] %></div>
			<% end %>
			
			<%= yield %>

		</section>
	</div>
</section>


<!-- footer -->
<footer class="group container">

	<h1 class="logo">
		<%= link_to "movietrail.er", movies_path %>
	</h1>

	<nav class="nav">
		<ul>
			<li><%= link_to "Add New Movie", new_movie_path %></li>
			<li><%= link_to "View All Trailers", trailers_path %></li>
			<li><a href="/about">About</a></li>
		</ul>
	</nav>

</footer>

</body>
</html>